In [174]:
import pandas as pd

In [175]:
know_2020 = pd.read_csv('../know_Data/train/KNOW_2020.csv')

C:\Users\user\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (179) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [176]:
know_2020

,idx,saq1_1,saq1_2,saq2_1,saq2_2,saq3_1,saq3_2,saq4_1,saq4_2,saq5_1,...,bq26,bq26_1,bq27_1,bq27_2,bq28,bq29,bq30_1,bq30_2,bq30_3,knowcode
0,27127,4,4,4,4,4,5,4,5,3,...,4,간호학,1,1,1,40,4000,2600,,304003
1,27128,5,6,5,6,4,5,4,5,4,...,4,기계공학,1,1,1,40,4000,3000,,221401
2,27129,3,4,3,4,3,4,3,5,3,...,4,기계,1,1,1,48,4300,3000,,815001
3,27130,4,5,2,3,3,3,4,5,3,...,4,보건학,1,1,1,40,3500,3300,,304003
4,27131,5,6,4,5,3,5,4,4,4,...,4,건축설비공학,1,1,1,40,5700,2700,,140201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8117,35244,4,6,3,5,3,3,1,,5,...,6,지구과학,1,1,1,40,5100,4000,,121105
8118,35245,3,4,4,5,2,4,4,6,1,...,4,광고학,1,1,1,45,3100,2600,,26102
8119,35246,5,6,3,4,3,4,4,5,5,...,4,국문,1,1,1,40,8000,3000,,31301
8120,35247,5,6,5,5,4,5,3,3,3,...,5,화학공학,1,1,1,40,5700,3200,,154105
8121,35248,2,5,4,6,3,5,4,5,3,...,3,조리학,1,1,1,46,3700,2700,,14201

## 이상치 파악

In [177]:
know_2020.info(verbose=1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8122 entries, 0 to 8121
Data columns (total 185 columns):
 #    Column    Dtype
---   ------    -----
 0    idx       int64
 1    saq1_1    int64
 2    saq1_2    object
 3    saq2_1    int64
 4    saq2_2    object
 5    saq3_1    int64
 6    saq3_2    object
 7    saq4_1    int64
 8    saq4_2    object
 9    saq5_1    int64
 10   saq5_2    object
 11   saq6_1    int64
 12   saq6_2    object
 13   saq7_1    int64
 14   saq7_2    object
 15   saq8_1    int64
 16   saq8_2    object
 17   saq9_1    int64
 18   saq9_2    object
 19   saq10_1   int64
 20   saq10_2   object
 21   saq11_1   int64
 22   saq11_2   object
 23   saq12_1   int64
 24   saq12_2   object
 25   saq13_1   int64
 26   saq13_2   object
 27   saq14_1   int64
 28   saq14_2   object
 29   saq15_1   int64
 30   saq15_2   object
 31   saq16_1   int64
 32   saq16_2   object
 33   saq17_1   int64
 34   saq17_2   object
 35   saq18_1   int64
 36   saq18_2   object
 37   saq19_1   int64
 38   saq19_2   object
 39   saq20_1   int64
 40   saq20_2   object
 41   saq21_1   int64
 42   saq21_2   object
 43   saq22_1   int64
 44   saq22_2   object
 45   saq23_1   int64
 46   saq23_2   object
 47   saq24_1   int64
 48   saq24_2   object
 49   saq25_1   int64
 50   saq25_2   object
 51   saq26_1   int64
 52   saq26_2   object
 53   saq27_1   int64
 54   saq27_2   object
 55   saq28_1   int64
 56   saq28_2   object
 57   saq29_1   int64
 58   saq29_2   object
 59   saq30_1   int64
 60   saq30_2   object
 61   saq31_1   int64
 62   saq31_2   object
 63   saq32_1   int64
 64   saq32_2   object
 65   saq33_1   int64
 66   saq33_2   object
 67   saq34_1   int64
 68   saq34_2   object
 69   saq35_1   int64
 70   saq35_2   object
 71   saq36_1   int64
 72   saq36_2   object
 73   saq37_1   int64
 74   saq37_2   object
 75   saq38_1   int64
 76   saq38_2   object
 77   saq39_1   int64
 78   saq39_2   object
 79   saq40_1   int64
 80   saq40_2   object
 81   saq41_1   int64
 82   saq41_2   object
 83   saq42_1   int64
 84   saq42_2   object
 85   saq43_1   int64
 86   saq43_2   object
 87   saq44_1   int64
 88   saq44_2   object
 89   vq1       int64
 90   vq2       int64
 91   vq3       int64
 92   vq4       int64
 93   vq5       int64
 94   vq6       int64
 95   vq7       int64
 96   vq8       int64
 97   vq9       int64
 98   vq10      int64
 99   vq11      int64
 100  vq12      int64
 101  vq13      int64
 102  bq1       int64
 103  bq2       int64
 104  bq3       int64
 105  bq4       int64
 106  bq4_1a    object
 107  bq4_1b    object
 108  bq4_1c    object
 109  bq5       int64
 110  bq5_1     object
 111  bq5_2     object
 112  bq6       int64
 113  bq7       int64
 114  bq8_1     int64
 115  bq8_2     int64
 116  bq8_3     int64
 117  bq9       int64
 118  bq10      int64
 119  bq11      int64
 120  bq12_1    int64
 121  bq12_2    int64
 122  bq12_3    int64
 123  bq12_4    int64
 124  bq12_5    int64
 125  bq13_1    int64
 126  bq13_2    int64
 127  bq13_3    int64
 128  bq14_1    int64
 129  bq14_2    int64
 130  bq14_3    int64
 131  bq14_4    int64
 132  bq14_5    int64
 133  bq14_6    int64
 134  bq14_7    int64
 135  bq15      int64
 136  bq16_1    int64
 137  bq16_2    int64
 138  bq16_3    int64
 139  bq16_4    int64
 140  bq16_5    int64
 141  bq16_6    int64
 142  bq16_7    int64
 143  bq16_8    int64
 144  bq16_9    int64
 145  bq16_10   int64
 146  bq17      int64
 147  bq18_1    int64
 148  bq18_2    int64
 149  bq18_3    int64
 150  bq18_4    int64
 151  bq18_5    int64
 152  bq18_6    int64
 153  bq18_7    int64
 154  bq18_8    int64
 155  bq18_9    int64
 156  bq18_10   object
 157  bq19      int64
 158  bq20      int64
 159  bq20_1    object
 160  bq21_1    int64
 161  bq21_2    int64
 162  bq21_3    int64
 163  bq21_4    int64
 164  bq22_1    int64
 165  bq22_2    int64
 166  bq22_3    int64
 167  bq22_4    int64
 168  bq22_5    int64
 169  bq22_6    int64
 170  bq23_1    int64
 171  bq23_2    int64
 172  bq23_3    int64
 173  bq24      int64
 174  bq25      int64
 175  bq26      int64
 176  bq26_1    object
 177  bq27_1    int64
 178  bq27_2    int64
 179  bq28      object
 180  bq29      int64
 181  bq30_1    object
 182  bq30_2    object
 183  bq30_3    object
 184  knowcode  int64
dtypes: int64(129), object(56)
memory usage: 11.5+ MB

In [178]:
know_2020[know_2020.bq18_10.isnull()==True].index

Int64Index([235], dtype='int64')

In [179]:
know_2020.isnull().sum()[150:]

bq18_4      0
bq18_5      0
bq18_6      0
bq18_7      0
bq18_8      0
bq18_9      0
bq18_10     1
bq19        0
bq20        0
bq20_1      0
bq21_1      0
bq21_2      0
bq21_3      0
bq21_4      0
bq22_1      0
bq22_2      0
bq22_3      0
bq22_4      0
bq22_5      0
bq22_6      0
bq23_1      0
bq23_2      0
bq23_3      0
bq24        0
bq25        0
bq26        0
bq26_1      0
bq27_1      0
bq27_2      0
bq28        0
bq29        0
bq30_1      0
bq30_2      0
bq30_3      0
knowcode    0
dtype: int64

In [180]:
for i in know_2020.columns : 
    print(i, len(know_2020[i].value_counts()))

idx 8122
saq1_1 5
saq1_2 8
saq2_1 5
saq2_2 8
saq3_1 5
saq3_2 8
saq4_1 5
saq4_2 8
saq5_1 5
saq5_2 8
saq6_1 5
saq6_2 8
saq7_1 5
saq7_2 8
saq8_1 5
saq8_2 8
saq9_1 5
saq9_2 8
saq10_1 5
saq10_2 8
saq11_1 5
saq11_2 8
saq12_1 5
saq12_2 8
saq13_1 5
saq13_2 8
saq14_1 5
saq14_2 8
saq15_1 5
saq15_2 8
saq16_1 5
saq16_2 8
saq17_1 5
saq17_2 8
saq18_1 5
saq18_2 8
saq19_1 5
saq19_2 8
saq20_1 5
saq20_2 8
saq21_1 5
saq21_2 8
saq22_1 5
saq22_2 8
saq23_1 5
saq23_2 8
saq24_1 5
saq24_2 8
saq25_1 5
saq25_2 8
saq26_1 5
saq26_2 8
saq27_1 5
saq27_2 8
saq28_1 5
saq28_2 8
saq29_1 5
saq29_2 8
saq30_1 5
saq30_2 8
saq31_1 5
saq31_2 8
saq32_1 5
saq32_2 8
saq33_1 5
saq33_2 8
saq34_1 5
saq34_2 8
saq35_1 5
saq35_2 8
saq36_1 5
saq36_2 8
saq37_1 5
saq37_2 8
saq38_1 5
saq38_2 8
saq39_1 5
saq39_2 8
saq40_1 5
saq40_2 8
saq41_1 5
saq41_2 8
saq42_1 5
saq42_2 8
saq43_1 5
saq43_2 8
saq44_1 5
saq44_2 8
vq1 5
vq2 5
vq3 5
vq4 5
vq5 5
vq6 5
vq7 5
vq8 5
vq9 5
vq10 5
vq11 5
vq12 5
vq13 5
bq1 21
bq2 5
bq3 6
bq4 2
bq4_1a 1632
bq4_1b 629
bq4_1c 182
bq5 2
bq5_1 7
bq5_2 1745
bq6 7
bq7 7
bq8_1 5
bq8_2 5
bq8_3 5
bq9 5
bq10 5
bq11 5
bq12_1 5
bq12_2 6
bq12_3 6
bq12_4 6
bq12_5 5
bq13_1 5
bq13_2 5
bq13_3 5
bq14_1 5
bq14_2 5
bq14_3 5
bq14_4 5
bq14_5 5
bq14_6 5
bq14_7 5
bq15 5
bq16_1 5
bq16_2 5
bq16_3 5
bq16_4 5
bq16_5 5
bq16_6 5
bq16_7 5
bq16_8 5
bq16_9 5
bq16_10 5
bq17 5
bq18_1 2
bq18_2 2
bq18_3 2
bq18_4 2
bq18_5 2
bq18_6 2
bq18_7 2
bq18_8 2
bq18_9 2
bq18_10 1314
bq19 5
bq20 5
bq20_1 6947
bq21_1 3
bq21_2 3
bq21_3 3
bq21_4 2
bq22_1 9
bq22_2 9
bq22_3 9
bq22_4 9
bq22_5 9
bq22_6 9
bq23_1 9
bq23_2 9
bq23_3 9
bq24 2
bq25 60
bq26 6
bq26_1 1088
bq27_1 2
bq27_2 7
bq28 5
bq29 58
bq30_1 329
bq30_2 208
bq30_3 102
knowcode 537

In [181]:
know_2020['bq28'].value_counts()

1    3685
1    3666
2     409
2     360
        2
Name: bq28, dtype: int64

1. 결측치 

bq18_10     1

2. 이상치

bq2 근무업체규모 5 / 기본값 6

bq28 5 type 

3. 주관식 문항

bq4_1a 자격증 1632
bq4_1b 자격증 629
bq4_1c 자격증 182

bq5_2 훈련사항 1745
bq18_10 직업세계변화 1314
bq20_1 일자리변화6947

bq26_1 학과 1088

4. 숫자여야하는 col
bq25 나이 60
bq29 근로시간 58
bq30_1 근로소득 329
bq30_2 근로소득 208
bq30_3 근로소득 102

5. 체크해봐야하는 col

bq22_1 9
bq22_2 9
bq22_3 9
bq22_4 9
bq22_5 9
bq22_6 9
bq23_1 9
bq23_2 9
bq23_3 9



bq27_1 2
bq27_2 7

## 이상치 처리

In [182]:
for col in know_2020:
        know_2020[col].replace(' ', 0, inplace = True)

In [183]:
know_2020.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8122 entries, 0 to 8121
Data columns (total 185 columns):
 #    Column    Dtype
---   ------    -----
 0    idx       int64
 1    saq1_1    int64
 2    saq1_2    object
 3    saq2_1    int64
 4    saq2_2    object
 5    saq3_1    int64
 6    saq3_2    object
 7    saq4_1    int64
 8    saq4_2    object
 9    saq5_1    int64
 10   saq5_2    object
 11   saq6_1    int64
 12   saq6_2    object
 13   saq7_1    int64
 14   saq7_2    object
 15   saq8_1    int64
 16   saq8_2    object
 17   saq9_1    int64
 18   saq9_2    object
 19   saq10_1   int64
 20   saq10_2   object
 21   saq11_1   int64
 22   saq11_2   object
 23   saq12_1   int64
 24   saq12_2   object
 25   saq13_1   int64
 26   saq13_2   object
 27   saq14_1   int64
 28   saq14_2   object
 29   saq15_1   int64
 30   saq15_2   object
 31   saq16_1   int64
 32   saq16_2   object
 33   saq17_1   int64
 34   saq17_2   object
 35   saq18_1   int64
 36   saq18_2   object
 37   saq19_1   int64
 38   saq19_2   object
 39   saq20_1   int64
 40   saq20_2   object
 41   saq21_1   int64
 42   saq21_2   object
 43   saq22_1   int64
 44   saq22_2   object
 45   saq23_1   int64
 46   saq23_2   object
 47   saq24_1   int64
 48   saq24_2   object
 49   saq25_1   int64
 50   saq25_2   object
 51   saq26_1   int64
 52   saq26_2   object
 53   saq27_1   int64
 54   saq27_2   object
 55   saq28_1   int64
 56   saq28_2   object
 57   saq29_1   int64
 58   saq29_2   object
 59   saq30_1   int64
 60   saq30_2   object
 61   saq31_1   int64
 62   saq31_2   object
 63   saq32_1   int64
 64   saq32_2   object
 65   saq33_1   int64
 66   saq33_2   object
 67   saq34_1   int64
 68   saq34_2   object
 69   saq35_1   int64
 70   saq35_2   object
 71   saq36_1   int64
 72   saq36_2   object
 73   saq37_1   int64
 74   saq37_2   object
 75   saq38_1   int64
 76   saq38_2   object
 77   saq39_1   int64
 78   saq39_2   object
 79   saq40_1   int64
 80   saq40_2   object
 81   saq41_1   int64
 82   saq41_2   object
 83   saq42_1   int64
 84   saq42_2   object
 85   saq43_1   int64
 86   saq43_2   object
 87   saq44_1   int64
 88   saq44_2   object
 89   vq1       int64
 90   vq2       int64
 91   vq3       int64
 92   vq4       int64
 93   vq5       int64
 94   vq6       int64
 95   vq7       int64
 96   vq8       int64
 97   vq9       int64
 98   vq10      int64
 99   vq11      int64
 100  vq12      int64
 101  vq13      int64
 102  bq1       int64
 103  bq2       int64
 104  bq3       int64
 105  bq4       int64
 106  bq4_1a    object
 107  bq4_1b    object
 108  bq4_1c    object
 109  bq5       int64
 110  bq5_1     object
 111  bq5_2     object
 112  bq6       int64
 113  bq7       int64
 114  bq8_1     int64
 115  bq8_2     int64
 116  bq8_3     int64
 117  bq9       int64
 118  bq10      int64
 119  bq11      int64
 120  bq12_1    int64
 121  bq12_2    int64
 122  bq12_3    int64
 123  bq12_4    int64
 124  bq12_5    int64
 125  bq13_1    int64
 126  bq13_2    int64
 127  bq13_3    int64
 128  bq14_1    int64
 129  bq14_2    int64
 130  bq14_3    int64
 131  bq14_4    int64
 132  bq14_5    int64
 133  bq14_6    int64
 134  bq14_7    int64
 135  bq15      int64
 136  bq16_1    int64
 137  bq16_2    int64
 138  bq16_3    int64
 139  bq16_4    int64
 140  bq16_5    int64
 141  bq16_6    int64
 142  bq16_7    int64
 143  bq16_8    int64
 144  bq16_9    int64
 145  bq16_10   int64
 146  bq17      int64
 147  bq18_1    int64
 148  bq18_2    int64
 149  bq18_3    int64
 150  bq18_4    int64
 151  bq18_5    int64
 152  bq18_6    int64
 153  bq18_7    int64
 154  bq18_8    int64
 155  bq18_9    int64
 156  bq18_10   object
 157  bq19      int64
 158  bq20      int64
 159  bq20_1    object
 160  bq21_1    int64
 161  bq21_2    int64
 162  bq21_3    int64
 163  bq21_4    int64
 164  bq22_1    int64
 165  bq22_2    int64
 166  bq22_3    int64
 167  bq22_4    int64
 168  bq22_5    int64
 169  bq22_6    int64
 170  bq23_1    int64
 171  bq23_2    int64
 172  bq23_3    int64
 173  bq24      int64
 174  bq25      int64
 175  bq26      int64
 176  bq26_1    object
 177  bq27_1    int64
 178  bq27_2    int64
 179  bq28      object
 180  bq29      int64
 181  bq30_1    object
 182  bq30_2    object
 183  bq30_3    object
 184  knowcode  int64
dtypes: int64(129), object(56)
memory usage: 11.5+ MB

In [184]:
# 주관식문항 

str_li =['bq4_1a','bq4_1b','bq4_1c','bq5_2', 'bq18_10','bq20_1','bq26_1']

In [185]:
for i in know_2020.columns : 
    if i not in str_li : 
        know_2020[i] = know_2020[i].astype(int)
    else : 
        know_2020[i] = know_2020[i].astype(str)

In [186]:
know_2020.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8122 entries, 0 to 8121
Data columns (total 185 columns):
 #    Column    Dtype
---   ------    -----
 0    idx       int32
 1    saq1_1    int32
 2    saq1_2    int32
 3    saq2_1    int32
 4    saq2_2    int32
 5    saq3_1    int32
 6    saq3_2    int32
 7    saq4_1    int32
 8    saq4_2    int32
 9    saq5_1    int32
 10   saq5_2    int32
 11   saq6_1    int32
 12   saq6_2    int32
 13   saq7_1    int32
 14   saq7_2    int32
 15   saq8_1    int32
 16   saq8_2    int32
 17   saq9_1    int32
 18   saq9_2    int32
 19   saq10_1   int32
 20   saq10_2   int32
 21   saq11_1   int32
 22   saq11_2   int32
 23   saq12_1   int32
 24   saq12_2   int32
 25   saq13_1   int32
 26   saq13_2   int32
 27   saq14_1   int32
 28   saq14_2   int32
 29   saq15_1   int32
 30   saq15_2   int32
 31   saq16_1   int32
 32   saq16_2   int32
 33   saq17_1   int32
 34   saq17_2   int32
 35   saq18_1   int32
 36   saq18_2   int32
 37   saq19_1   int32
 38   saq19_2   int32
 39   saq20_1   int32
 40   saq20_2   int32
 41   saq21_1   int32
 42   saq21_2   int32
 43   saq22_1   int32
 44   saq22_2   int32
 45   saq23_1   int32
 46   saq23_2   int32
 47   saq24_1   int32
 48   saq24_2   int32
 49   saq25_1   int32
 50   saq25_2   int32
 51   saq26_1   int32
 52   saq26_2   int32
 53   saq27_1   int32
 54   saq27_2   int32
 55   saq28_1   int32
 56   saq28_2   int32
 57   saq29_1   int32
 58   saq29_2   int32
 59   saq30_1   int32
 60   saq30_2   int32
 61   saq31_1   int32
 62   saq31_2   int32
 63   saq32_1   int32
 64   saq32_2   int32
 65   saq33_1   int32
 66   saq33_2   int32
 67   saq34_1   int32
 68   saq34_2   int32
 69   saq35_1   int32
 70   saq35_2   int32
 71   saq36_1   int32
 72   saq36_2   int32
 73   saq37_1   int32
 74   saq37_2   int32
 75   saq38_1   int32
 76   saq38_2   int32
 77   saq39_1   int32
 78   saq39_2   int32
 79   saq40_1   int32
 80   saq40_2   int32
 81   saq41_1   int32
 82   saq41_2   int32
 83   saq42_1   int32
 84   saq42_2   int32
 85   saq43_1   int32
 86   saq43_2   int32
 87   saq44_1   int32
 88   saq44_2   int32
 89   vq1       int32
 90   vq2       int32
 91   vq3       int32
 92   vq4       int32
 93   vq5       int32
 94   vq6       int32
 95   vq7       int32
 96   vq8       int32
 97   vq9       int32
 98   vq10      int32
 99   vq11      int32
 100  vq12      int32
 101  vq13      int32
 102  bq1       int32
 103  bq2       int32
 104  bq3       int32
 105  bq4       int32
 106  bq4_1a    object
 107  bq4_1b    object
 108  bq4_1c    object
 109  bq5       int32
 110  bq5_1     int32
 111  bq5_2     object
 112  bq6       int32
 113  bq7       int32
 114  bq8_1     int32
 115  bq8_2     int32
 116  bq8_3     int32
 117  bq9       int32
 118  bq10      int32
 119  bq11      int32
 120  bq12_1    int32
 121  bq12_2    int32
 122  bq12_3    int32
 123  bq12_4    int32
 124  bq12_5    int32
 125  bq13_1    int32
 126  bq13_2    int32
 127  bq13_3    int32
 128  bq14_1    int32
 129  bq14_2    int32
 130  bq14_3    int32
 131  bq14_4    int32
 132  bq14_5    int32
 133  bq14_6    int32
 134  bq14_7    int32
 135  bq15      int32
 136  bq16_1    int32
 137  bq16_2    int32
 138  bq16_3    int32
 139  bq16_4    int32
 140  bq16_5    int32
 141  bq16_6    int32
 142  bq16_7    int32
 143  bq16_8    int32
 144  bq16_9    int32
 145  bq16_10   int32
 146  bq17      int32
 147  bq18_1    int32
 148  bq18_2    int32
 149  bq18_3    int32
 150  bq18_4    int32
 151  bq18_5    int32
 152  bq18_6    int32
 153  bq18_7    int32
 154  bq18_8    int32
 155  bq18_9    int32
 156  bq18_10   object
 157  bq19      int32
 158  bq20      int32
 159  bq20_1    object
 160  bq21_1    int32
 161  bq21_2    int32
 162  bq21_3    int32
 163  bq21_4    int32
 164  bq22_1    int32
 165  bq22_2    int32
 166  bq22_3    int32
 167  bq22_4    int32
 168  bq22_5    int32
 169  bq22_6    int32
 170  bq23_1    int32
 171  bq23_2    int32
 172  bq23_3    int32
 173  bq24      int32
 174  bq25      int32
 175  bq26      int32
 176  bq26_1    object
 177  bq27_1    int32
 178  bq27_2    int32
 179  bq28      int32
 180  bq29      int32
 181  bq30_1    int32
 182  bq30_2    int32
 183  bq30_3    int32
 184  knowcode  int32
dtypes: int32(178), object(7)
memory usage: 5.9+ MB

In [187]:
## _1에서 1을 선택한 사람중 _2를 답변한 사람이 있는지 확인

for i in range(44) :
    str5 = 'saq' + str(i+1) +'_1'
    str6 = 'saq' + str(i+1) +'_2'
    
    print(know_2020[(know_2020[str5]==1) & (know_2020[str6]!=0)][str6])

Series([], Name: saq1_2, dtype: int32)
Series([], Name: saq2_2, dtype: int32)
Series([], Name: saq3_2, dtype: int32)
Series([], Name: saq4_2, dtype: int32)
Series([], Name: saq5_2, dtype: int32)
Series([], Name: saq6_2, dtype: int32)
Series([], Name: saq7_2, dtype: int32)
Series([], Name: saq8_2, dtype: int32)
Series([], Name: saq9_2, dtype: int32)
Series([], Name: saq10_2, dtype: int32)
Series([], Name: saq11_2, dtype: int32)
Series([], Name: saq12_2, dtype: int32)
Series([], Name: saq13_2, dtype: int32)
Series([], Name: saq14_2, dtype: int32)
Series([], Name: saq15_2, dtype: int32)
Series([], Name: saq16_2, dtype: int32)
Series([], Name: saq17_2, dtype: int32)
Series([], Name: saq18_2, dtype: int32)
Series([], Name: saq19_2, dtype: int32)
Series([], Name: saq20_2, dtype: int32)
Series([], Name: saq21_2, dtype: int32)
Series([], Name: saq22_2, dtype: int32)
Series([], Name: saq23_2, dtype: int32)
Series([], Name: saq24_2, dtype: int32)
Series([], Name: saq25_2, dtype: int32)
Series([], Name: saq26_2, dtype: int32)
Series([], Name: saq27_2, dtype: int32)
Series([], Name: saq28_2, dtype: int32)
Series([], Name: saq29_2, dtype: int32)
Series([], Name: saq30_2, dtype: int32)
Series([], Name: saq31_2, dtype: int32)
Series([], Name: saq32_2, dtype: int32)
Series([], Name: saq33_2, dtype: int32)
Series([], Name: saq34_2, dtype: int32)
Series([], Name: saq35_2, dtype: int32)
Series([], Name: saq36_2, dtype: int32)
Series([], Name: saq37_2, dtype: int32)
Series([], Name: saq38_2, dtype: int32)
Series([], Name: saq39_2, dtype: int32)
2177    4
Name: saq40_2, dtype: int32
Series([], Name: saq41_2, dtype: int32)
Series([], Name: saq42_2, dtype: int32)
Series([], Name: saq43_2, dtype: int32)
Series([], Name: saq44_2, dtype: int32)

In [188]:
know_2020.iloc[2177, 80] = 0

In [189]:
## 결측치 파악(답변있어야하는 셀 )

for i in range(44) :
    str5 = 'saq' + str(i+1) +'_1'
    str6 = 'saq' + str(i+1) +'_2'
    
    print(know_2020[(know_2020[str5].isin([2,3,4,5])) & (know_2020[str6]==0)][str6])
    
#선택질문 중 빈셀 없음

Series([], Name: saq1_2, dtype: int32)
Series([], Name: saq2_2, dtype: int32)
Series([], Name: saq3_2, dtype: int32)
Series([], Name: saq4_2, dtype: int32)
Series([], Name: saq5_2, dtype: int32)
Series([], Name: saq6_2, dtype: int32)
Series([], Name: saq7_2, dtype: int32)
Series([], Name: saq8_2, dtype: int32)
Series([], Name: saq9_2, dtype: int32)
Series([], Name: saq10_2, dtype: int32)
Series([], Name: saq11_2, dtype: int32)
Series([], Name: saq12_2, dtype: int32)
Series([], Name: saq13_2, dtype: int32)
Series([], Name: saq14_2, dtype: int32)
Series([], Name: saq15_2, dtype: int32)
Series([], Name: saq16_2, dtype: int32)
Series([], Name: saq17_2, dtype: int32)
Series([], Name: saq18_2, dtype: int32)
Series([], Name: saq19_2, dtype: int32)
Series([], Name: saq20_2, dtype: int32)
Series([], Name: saq21_2, dtype: int32)
Series([], Name: saq22_2, dtype: int32)
Series([], Name: saq23_2, dtype: int32)
Series([], Name: saq24_2, dtype: int32)
Series([], Name: saq25_2, dtype: int32)
Series([], Name: saq26_2, dtype: int32)
Series([], Name: saq27_2, dtype: int32)
Series([], Name: saq28_2, dtype: int32)
Series([], Name: saq29_2, dtype: int32)
Series([], Name: saq30_2, dtype: int32)
Series([], Name: saq31_2, dtype: int32)
Series([], Name: saq32_2, dtype: int32)
Series([], Name: saq33_2, dtype: int32)
Series([], Name: saq34_2, dtype: int32)
Series([], Name: saq35_2, dtype: int32)
Series([], Name: saq36_2, dtype: int32)
Series([], Name: saq37_2, dtype: int32)
Series([], Name: saq38_2, dtype: int32)
Series([], Name: saq39_2, dtype: int32)
Series([], Name: saq40_2, dtype: int32)
Series([], Name: saq41_2, dtype: int32)
Series([], Name: saq42_2, dtype: int32)
Series([], Name: saq43_2, dtype: int32)
Series([], Name: saq44_2, dtype: int32)

1. 주관식 항목 drop예정으로 확인 안함 

bq18_10 bq20_1

2. 학과
bq26_1 빈셀 없음

3. bq27_1 ~ bq30_3
bq28,29 는 조건에 맞게 대답하려면 빈칸이 많아야하는데 그렇지 않음 그냥 빈셀을 채워주는 식으로 처리 할 예정 

bq28 빈셀 2개 
28965(1838) -> 2 
30547(3420) -> 1


bq29 빈셀 없음

2017과 동일하게 처리 bq30_1 빈셀 1개 bq30_2 빈셀 3개 bq30_3 빈셀 없음

In [190]:
know_2020.iloc[1838,179]=2

In [191]:
know_2020.iloc[3420,179]=1

In [192]:
null_li = know_2020[(know_2020.bq27_1==1) & (know_2020.bq30_1==0)].index
null_li

Int64Index([1854], dtype='int64')

In [193]:
for i in null_li:
      know_2020.iloc[i,181]= round(know_2020[(know_2020.bq1 ==know_2020.iloc[i,102])&(know_2020.bq30_1!=0)].bq30_1.mean())

In [194]:
null_li = know_2020[(know_2020.bq27_1==1) & (know_2020.bq30_1==0)].index
null_li

Int64Index([], dtype='int64')

In [195]:
null_li2 = know_2020[(know_2020.bq27_1==1) & (know_2020.bq30_2==0)].index
null_li2

Int64Index([4172, 4882, 7430], dtype='int64')

In [196]:
for i in null_li2:
      know_2020.iloc[i,182]= round(know_2020[(know_2020.bq1 ==know_2020.iloc[i,102])&(know_2020.bq30_2!=0)].bq30_2.mean())

In [197]:
null_li2 = know_2020[(know_2020.bq27_1==1) & (know_2020.bq30_2==0)].index
null_li2

Int64Index([], dtype='int64')

In [198]:
## 자격증 없음 

know_2020['bq4_1b'].replace(0, '0', inplace = True)


for i in know_2020.bq4_1b:
    if '없' in i : 
        print(i)

know_2020['bq4_1b'].replace('없다', '0', inplace = True)

없다
없다
없다
없다
없다
없다
없다
없다
없다
없다
없다
없다
없다
없다
없다
없다

In [199]:
for i in know_2020.bq4_1b:
    if '없' in i : 
        print(i)

In [200]:
know_2020.to_csv("know_2020_enutf.csv", encoding='utf8', index=False)
know_2020.to_csv("know_2020_encp.csv", encoding='cp949', index=False)

In [201]:
df_cp = pd.read_csv("know_2020_encp.csv", encoding='cp949')
df_cp.info(verbose=1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8122 entries, 0 to 8121
Data columns (total 185 columns):
 #    Column    Dtype
---   ------    -----
 0    idx       int64
 1    saq1_1    int64
 2    saq1_2    int64
 3    saq2_1    int64
 4    saq2_2    int64
 5    saq3_1    int64
 6    saq3_2    int64
 7    saq4_1    int64
 8    saq4_2    int64
 9    saq5_1    int64
 10   saq5_2    int64
 11   saq6_1    int64
 12   saq6_2    int64
 13   saq7_1    int64
 14   saq7_2    int64
 15   saq8_1    int64
 16   saq8_2    int64
 17   saq9_1    int64
 18   saq9_2    int64
 19   saq10_1   int64
 20   saq10_2   int64
 21   saq11_1   int64
 22   saq11_2   int64
 23   saq12_1   int64
 24   saq12_2   int64
 25   saq13_1   int64
 26   saq13_2   int64
 27   saq14_1   int64
 28   saq14_2   int64
 29   saq15_1   int64
 30   saq15_2   int64
 31   saq16_1   int64
 32   saq16_2   int64
 33   saq17_1   int64
 34   saq17_2   int64
 35   saq18_1   int64
 36   saq18_2   int64
 37   saq19_1   int64
 38   saq19_2   int64
 39   saq20_1   int64
 40   saq20_2   int64
 41   saq21_1   int64
 42   saq21_2   int64
 43   saq22_1   int64
 44   saq22_2   int64
 45   saq23_1   int64
 46   saq23_2   int64
 47   saq24_1   int64
 48   saq24_2   int64
 49   saq25_1   int64
 50   saq25_2   int64
 51   saq26_1   int64
 52   saq26_2   int64
 53   saq27_1   int64
 54   saq27_2   int64
 55   saq28_1   int64
 56   saq28_2   int64
 57   saq29_1   int64
 58   saq29_2   int64
 59   saq30_1   int64
 60   saq30_2   int64
 61   saq31_1   int64
 62   saq31_2   int64
 63   saq32_1   int64
 64   saq32_2   int64
 65   saq33_1   int64
 66   saq33_2   int64
 67   saq34_1   int64
 68   saq34_2   int64
 69   saq35_1   int64
 70   saq35_2   int64
 71   saq36_1   int64
 72   saq36_2   int64
 73   saq37_1   int64
 74   saq37_2   int64
 75   saq38_1   int64
 76   saq38_2   int64
 77   saq39_1   int64
 78   saq39_2   int64
 79   saq40_1   int64
 80   saq40_2   int64
 81   saq41_1   int64
 82   saq41_2   int64
 83   saq42_1   int64
 84   saq42_2   int64
 85   saq43_1   int64
 86   saq43_2   int64
 87   saq44_1   int64
 88   saq44_2   int64
 89   vq1       int64
 90   vq2       int64
 91   vq3       int64
 92   vq4       int64
 93   vq5       int64
 94   vq6       int64
 95   vq7       int64
 96   vq8       int64
 97   vq9       int64
 98   vq10      int64
 99   vq11      int64
 100  vq12      int64
 101  vq13      int64
 102  bq1       int64
 103  bq2       int64
 104  bq3       int64
 105  bq4       int64
 106  bq4_1a    object
 107  bq4_1b    object
 108  bq4_1c    object
 109  bq5       int64
 110  bq5_1     int64
 111  bq5_2     object
 112  bq6       int64
 113  bq7       int64
 114  bq8_1     int64
 115  bq8_2     int64
 116  bq8_3     int64
 117  bq9       int64
 118  bq10      int64
 119  bq11      int64
 120  bq12_1    int64
 121  bq12_2    int64
 122  bq12_3    int64
 123  bq12_4    int64
 124  bq12_5    int64
 125  bq13_1    int64
 126  bq13_2    int64
 127  bq13_3    int64
 128  bq14_1    int64
 129  bq14_2    int64
 130  bq14_3    int64
 131  bq14_4    int64
 132  bq14_5    int64
 133  bq14_6    int64
 134  bq14_7    int64
 135  bq15      int64
 136  bq16_1    int64
 137  bq16_2    int64
 138  bq16_3    int64
 139  bq16_4    int64
 140  bq16_5    int64
 141  bq16_6    int64
 142  bq16_7    int64
 143  bq16_8    int64
 144  bq16_9    int64
 145  bq16_10   int64
 146  bq17      int64
 147  bq18_1    int64
 148  bq18_2    int64
 149  bq18_3    int64
 150  bq18_4    int64
 151  bq18_5    int64
 152  bq18_6    int64
 153  bq18_7    int64
 154  bq18_8    int64
 155  bq18_9    int64
 156  bq18_10   object
 157  bq19      int64
 158  bq20      int64
 159  bq20_1    object
 160  bq21_1    int64
 161  bq21_2    int64
 162  bq21_3    int64
 163  bq21_4    int64
 164  bq22_1    int64
 165  bq22_2    int64
 166  bq22_3    int64
 167  bq22_4    int64
 168  bq22_5    int64
 169  bq22_6    int64
 170  bq23_1    int64
 171  bq23_2    int64
 172  bq23_3    int64
 173  bq24      int64
 174  bq25      int64
 175  bq26      int64
 176  bq26_1    object
 177  bq27_1    int64
 178  bq27_2    int64
 179  bq28      int64
 180  bq29      int64
 181  bq30_1    int64
 182  bq30_2    int64
 183  bq30_3    int64
 184  knowcode  int64
dtypes: int64(178), object(7)
memory usage: 11.5+ MB

In [202]:
df_utf = pd.read_csv("know_2020_enutf.csv")
df_utf.info(verbose=1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8122 entries, 0 to 8121
Data columns (total 185 columns):
 #    Column    Dtype
---   ------    -----
 0    idx       int64
 1    saq1_1    int64
 2    saq1_2    int64
 3    saq2_1    int64
 4    saq2_2    int64
 5    saq3_1    int64
 6    saq3_2    int64
 7    saq4_1    int64
 8    saq4_2    int64
 9    saq5_1    int64
 10   saq5_2    int64
 11   saq6_1    int64
 12   saq6_2    int64
 13   saq7_1    int64
 14   saq7_2    int64
 15   saq8_1    int64
 16   saq8_2    int64
 17   saq9_1    int64
 18   saq9_2    int64
 19   saq10_1   int64
 20   saq10_2   int64
 21   saq11_1   int64
 22   saq11_2   int64
 23   saq12_1   int64
 24   saq12_2   int64
 25   saq13_1   int64
 26   saq13_2   int64
 27   saq14_1   int64
 28   saq14_2   int64
 29   saq15_1   int64
 30   saq15_2   int64
 31   saq16_1   int64
 32   saq16_2   int64
 33   saq17_1   int64
 34   saq17_2   int64
 35   saq18_1   int64
 36   saq18_2   int64
 37   saq19_1   int64
 38   saq19_2   int64
 39   saq20_1   int64
 40   saq20_2   int64
 41   saq21_1   int64
 42   saq21_2   int64
 43   saq22_1   int64
 44   saq22_2   int64
 45   saq23_1   int64
 46   saq23_2   int64
 47   saq24_1   int64
 48   saq24_2   int64
 49   saq25_1   int64
 50   saq25_2   int64
 51   saq26_1   int64
 52   saq26_2   int64
 53   saq27_1   int64
 54   saq27_2   int64
 55   saq28_1   int64
 56   saq28_2   int64
 57   saq29_1   int64
 58   saq29_2   int64
 59   saq30_1   int64
 60   saq30_2   int64
 61   saq31_1   int64
 62   saq31_2   int64
 63   saq32_1   int64
 64   saq32_2   int64
 65   saq33_1   int64
 66   saq33_2   int64
 67   saq34_1   int64
 68   saq34_2   int64
 69   saq35_1   int64
 70   saq35_2   int64
 71   saq36_1   int64
 72   saq36_2   int64
 73   saq37_1   int64
 74   saq37_2   int64
 75   saq38_1   int64
 76   saq38_2   int64
 77   saq39_1   int64
 78   saq39_2   int64
 79   saq40_1   int64
 80   saq40_2   int64
 81   saq41_1   int64
 82   saq41_2   int64
 83   saq42_1   int64
 84   saq42_2   int64
 85   saq43_1   int64
 86   saq43_2   int64
 87   saq44_1   int64
 88   saq44_2   int64
 89   vq1       int64
 90   vq2       int64
 91   vq3       int64
 92   vq4       int64
 93   vq5       int64
 94   vq6       int64
 95   vq7       int64
 96   vq8       int64
 97   vq9       int64
 98   vq10      int64
 99   vq11      int64
 100  vq12      int64
 101  vq13      int64
 102  bq1       int64
 103  bq2       int64
 104  bq3       int64
 105  bq4       int64
 106  bq4_1a    object
 107  bq4_1b    object
 108  bq4_1c    object
 109  bq5       int64
 110  bq5_1     int64
 111  bq5_2     object
 112  bq6       int64
 113  bq7       int64
 114  bq8_1     int64
 115  bq8_2     int64
 116  bq8_3     int64
 117  bq9       int64
 118  bq10      int64
 119  bq11      int64
 120  bq12_1    int64
 121  bq12_2    int64
 122  bq12_3    int64
 123  bq12_4    int64
 124  bq12_5    int64
 125  bq13_1    int64
 126  bq13_2    int64
 127  bq13_3    int64
 128  bq14_1    int64
 129  bq14_2    int64
 130  bq14_3    int64
 131  bq14_4    int64
 132  bq14_5    int64
 133  bq14_6    int64
 134  bq14_7    int64
 135  bq15      int64
 136  bq16_1    int64
 137  bq16_2    int64
 138  bq16_3    int64
 139  bq16_4    int64
 140  bq16_5    int64
 141  bq16_6    int64
 142  bq16_7    int64
 143  bq16_8    int64
 144  bq16_9    int64
 145  bq16_10   int64
 146  bq17      int64
 147  bq18_1    int64
 148  bq18_2    int64
 149  bq18_3    int64
 150  bq18_4    int64
 151  bq18_5    int64
 152  bq18_6    int64
 153  bq18_7    int64
 154  bq18_8    int64
 155  bq18_9    int64
 156  bq18_10   object
 157  bq19      int64
 158  bq20      int64
 159  bq20_1    object
 160  bq21_1    int64
 161  bq21_2    int64
 162  bq21_3    int64
 163  bq21_4    int64
 164  bq22_1    int64
 165  bq22_2    int64
 166  bq22_3    int64
 167  bq22_4    int64
 168  bq22_5    int64
 169  bq22_6    int64
 170  bq23_1    int64
 171  bq23_2    int64
 172  bq23_3    int64
 173  bq24      int64
 174  bq25      int64
 175  bq26      int64
 176  bq26_1    object
 177  bq27_1    int64
 178  bq27_2    int64
 179  bq28      int64
 180  bq29      int64
 181  bq30_1    int64
 182  bq30_2    int64
 183  bq30_3    int64
 184  knowcode  int64
dtypes: int64(178), object(7)
memory usage: 11.5+ MB